import React, { useState } from "react";
import { PlusIcon, TrashIcon, Sparkles, Loader2 } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { useSelector } from "react-redux";
import toast from "react-hot-toast";
import api from "../configs/api";

function ExperienceForm({ data, onChange }) {
  const { token } = useSelector((state) => state.auth);
  // State to track which experience description is currently being generated by AI
  const [generatingIndex, setGeneratingIndex] = useState(-1);

  const addExperience = () => {
    const newExperience = {
      company: "",
      position: "",
      start_date: "",
      end_date: "",
      description: "",
      is_current: false,
    };
    onChange([...data, newExperience]);
  };

  const removeExperience = (index) => {
    const updated = data.filter((_, i) => i !== index);
    onChange(updated);
  };

  const updateExperience = (index, field, value) => {
    const updated = [...data];
    updated[index] = { ...updated[index], [field]: value };
    onChange(updated);
  };

  const generateDescription = async (index) => {
    setGeneratingIndex(index);
    const experience = data[index];
    const prompt = `enhance my job description: "${experience.description}" for the position of ${experience.position} at ${experience.company}.`;
    try {
      const { data } = await api.post(
        "/api/ai/enhance-job-desc",
        { userContent: prompt },
        { headers: { Authorization: token } },
      );
      updateExperience(index, "description", data.enhancedContent);
    } catch (error) {
      toast.error(error.message);
    } finally {
      setGeneratingIndex(-1);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="flex items-center gap-2 text-lg font-semibold text-gray-900">
            Professional Experience
          </h3>
          <p className="text-sm text-gray-500">Add your job experience</p>
        </div>

        {/* Add Experience Button */}
        <button
          onClick={addExperience}
          className="flex items-center gap-2 px-3 py-1 text-sm bg-green-100 text-green-700 rounded hover:bg-green-200 transition-colors"
        >
          <PlusIcon className="size-4" />
          Add Experience
        </button>
      </div>

      {/* Experience Cards */}
      {data.map((exp, index) => (
        <div
          key={index}
          className="border border-gray-200 rounded-lg p-4 space-y-3"
        >
          {/* Card Header */}
          <div className="flex items-center justify-between">
            <h4 className="font-medium text-gray-700">
              Experience #{index + 1}
            </h4>
            <button
              onClick={() => removeExperience(index)}
              className="text-red-400 hover:text-red-600 transition-colors"
            >
              <TrashIcon className="size-5" />
            </button>
          </div>

          {/* Company + Job Title */}
          <div className="grid grid-cols-2 gap-3">
            <input
              type="text"
              placeholder="Company Name"
              value={exp.company || ""}
              onChange={(e) =>
                updateExperience(index, "company", e.target.value)
              }
              className="px-3 py-2 text-sm"
            />
            <input
              type="text"
              placeholder="Job Title"
              value={exp.position || ""}
              onChange={(e) =>
                updateExperience(index, "position", e.target.value)
              }
              className="px-3 py-2 text-sm"
            />
          </div>

          {/* Start + End Date */}
          <div className="grid grid-cols-2 gap-3">
            <input
              type="date"
              value={exp.start_date || ""}
              onChange={(e) =>
                updateExperience(index, "start_date", e.target.value)
              }
              className="px-3 py-2 text-sm"
            />
            <input
              type="date"
              value={exp.end_date || ""}
              onChange={(e) =>
                updateExperience(index, "end_date", e.target.value)
              }
              disabled={exp.is_current}
              className="px-3 py-2 text-sm disabled:opacity-50"
            />
          </div>

          {/* Currently Working Here */}
          <label className="flex items-center gap-2 text-sm text-gray-600 cursor-pointer">
            <input
              type="checkbox"
              checked={exp.is_current || false}
              onChange={(e) =>
                updateExperience(index, "is_current", e.target.checked)
              }
            />
            Currently working here
          </label>

          {/* Job Description */}
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-sm font-medium text-gray-700">
                Job Description
              </label>
              <button
                onClick ={() => generateDescription(index)}
                disabled={
                  generatingIndex === index ||
                  !exp.position ||
                  !exp.company
                }
                className="flex items-center gap-1 text-xs text-purple-500 hover:text-purple-700 transition-colors"
              >
                {/* Loader or Sparkles icon based on generation status */}
                {generatingIndex === index ? (
                  <Loader2 className="w-3 h-3 animate-spin" />
                ) : (
                  // Sparkles icon
                  <Sparkles className="w-3 h-3 text-purple-500" />
                )}
                {generatingIndex === index ? "Enhancing..." : "Enhance with AI"}
                
              </button>


            </div>
            <textarea
              rows={4}
              placeholder="Describe your key responsibilities and achievements..."
              value={exp.description || ""}
              onChange={(e) =>
                updateExperience(index, "description", e.target.value)
              }
              className="w-full px-3 py-2 text-sm resize-none"
            />
          </div>
        </div>
      ))}
    </div>
  );
}

export default ExperienceForm;
